apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: {{ .Values.namespace.name }}
{{- if .Values.adservice.annotations }}
  annotations:
{{ toYaml .Values.adservice.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.adservice.image.repository }}:{{ .Values.adservice.image.tag }}
        ports:
        - containerPort: {{ .Values.adservice.containerPort }}
        env:
        - name: PORT
          value: {{ .Values.adservice.envPortValue }}
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: {{ .Values.adservice.readinessProbe.exec.command }}
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: {{ .Values.adservice.livenessProbe.exec.command }}
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: {{ .Values.adservice.service.port }}
    targetPort: {{ .Values.adservice.service.targetPort }}
