apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.currencyservice.image.repository }}:{{ .Values.currencyservice.image.tag }}
        ports:
        - name: grpc
          containerPort: {{ .Values.currencyservice.containerPort }}
        env:
        - name: PORT
          value: {{ .Values.currencyservice.envPortValue }}
        readinessProbe:
          exec:
            command: {{ .Values.currencyservice.readinessProbe.exec.command }}
        livenessProbe:
          exec:
            command: {{ .Values.currencyservice.livenessProbe.exec.command }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: {{ .Values.currencyservice.service.port }}
    targetPort: {{ .Values.currencyservice.service.targetPort }}
