apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
          - containerPort: {{ .Values.frontend.containerPort }}
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.httpGetport }}
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: {{ .Values.frontend.httpGetport }}
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: {{ .Values.frontend.envPortValue }}
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: {{ .Values.frontend.envProductcatalogserviceAddr }}
          - name: CURRENCY_SERVICE_ADDR
            value: {{ .Values.frontend.envCurrencyserviceAddr }}
          - name: AD_SERVICE_ADDR
            value: {{ .Values.frontend.envAdserviceAddr }}
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.frontend.ports.port }}
    targetPort: {{ .Values.frontend.ports.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-nodeport
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.frontend.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.frontend.ports.targetPort }}
    nodePort: {{ .Values.frontend.ports.nodePort }}
  selector:
    app: frontend
  type: NodePort
