apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.productcatalogservice.image.repository }}:{{ .Values.productcatalogservice.image.tag }}
        ports:
        - containerPort: {{ .Values.productcatalogservice.containerPort }}
        env:
        - name: PORT
          value: {{ .Values.productcatalogservice.envPortValue }}
        readinessProbe:
          exec:
            command: {{ .Values.productcatalogservice.readinessProbe.exec.command }}
        livenessProbe:
          exec:
            command: {{ .Values.productcatalogservice.livenessProbe.exec.command }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: {{ .Values.productcatalogservice.service.port }}
    targetPort: {{ .Values.productcatalogservice.service.targetPort }}
