apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-grafana
  name: grafana-nodeport
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30030
  selector:
    app: prometheus-grafana
  type: NodePort
