apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev 
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-dev.yaml
    path: helm
    repoURL: https://github.com/moebius5/nd064_capstone_starter
    targetRevision: HEAD
  syncPolicy: 
    automated: {}
