adservice:    
  image:
    repository: moebius5/adservice
    tag:  latest
  containerPort: 9555
  envPortValue: '"9555"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:9555"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:9555"]'
  service:
    port: 9555
    targetPort: 9555






currencyservice:
  image:
    repository: moebius5/currencyservice
    tag:  latest
  containerPort: 7000
  envPortValue: '"7000"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:7000"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:7000"]'
  service:
    port: 7000
    targetPort: 7000

frontend:
  image:
    repository: moebius5/frontend
    tag:  latest
  containerPort: 8080
  httpGetport: 8080
  envPortValue: '"8080"'
  envProductcatalogserviceAddr: '"productcatalogservice:3550"'
  envCurrencyserviceAddr: '"currencyservice:7000"'
  envAdserviceAddr: '"adservice:9555"'
  ports:
    port: 80
    targetPort: 8080
    nodePort: 30039


productcatalogservice:
  image:
    repository: moebius5/productcatalogservice
    tag:  latest
  containerPort: 3550
  envPortValue: '"3550"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:3550"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:3550"]'
  service:
    port: 3550
    targetPort: 3550
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  