namespace:
  name: dev-v2


adservice:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  image:
    repository: moebius5/adservice-v2
    tag:  sha-b38b7b9
  containerPort: 9556
  envPortValue: '"9556"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:9556"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:9556"]'
  service:
    port: 9556
    targetPort: 9556


currencyservice:
  image:
    repository: moebius5/currencyservice
    tag:  sha-b38b7b9
  containerPort: 7000
  envPortValue: '"7000"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:7000"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:7000"]'
  service:
    port: 7000
    targetPort: 7000


frontend:
  image:
    repository: moebius5/frontend
    tag:  sha-b38b7b9
  containerPort: 8080
  httpGetport: 8080
  envPortValue: '"8080"'
  envProductcatalogserviceAddr: '"productcatalogservice:3550"'
  envCurrencyserviceAddr: '"currencyservice:7000"'
  envAdserviceAddr: '"adservice:9556"'
  ports:
    port: 80
    targetPort: 8080
    nodePort: 30038


productcatalogservice:
  image:
    repository: moebius5/productcatalogservice
    tag:  sha-b38b7b9
  containerPort: 3550
  envPortValue: '"3550"'
  readinessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:3550"]'
  livenessProbe:
    exec:
      command: '["/bin/grpc_health_probe", "-addr=:3550"]'
  service:
    port: 3550
    targetPort: 3550