name: Uda'CityShop [latest tag] - Package with Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push latest
        id: frontend_build
        uses: docker/build-push-action@v2
        with:
          context: /src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: moebius5/frontend:latest
      -
        name: Build and push latest
        id: productcatalogservice_build
        uses: docker/build-push-action@v2
        with:
          context: /src/productcatalogservice
          file: ./src/productcatalogservice/Dockerfile
          push: true
          tags: moebius5/productcatalogservice:latest
      -
        name: Build and push latest
        id: currencyservice_build
        uses: docker/build-push-action@v2
        with:
          context: /src/currencyservice
          file: ./src/currencyservice/Dockerfile
          push: true
          tags: moebius5/currencyservice:latest
      -
        name: Build and push latest
        id: adservice_build
        uses: docker/build-push-action@v2
        with:
          context: /src/adservice
          file: ./src/adservice/Dockerfile
          push: true
          tags: moebius5/adservice:latest
